// GENERERAD FIL — ändra inte för hand. Byggs om med:
//   Price_engine/Price_engine/.venv/bin/python scripts/build_brands.py > web/src/lib/brands.ts
//
// Märken prismotorn faktiskt har underlag för. Medlemskapet har två källor: korpusens egen
// `brand`-kolumn (116 märken, tas alla med) och en kandidatlista över kända möbel- och
// designnamn, som utelämnas när de saknar träffar. Ett märke i väljaren som motorn inte
// hittar en enda annons för vore ett löfte vi inte kan hålla.
//
// `listings` är MÄTT PÅ ANNONSTEXTEN för alla, aldrig ur `brand`-kolumnen: kolumnen är ifylld
// på 2,3 % av korpusen, och en sortering som blandade de två skalorna la IKEA under en
// designer med färre annonser. Talet är ett stickprov uppskalat — en storleksordning, inte
// en exakt räkning.
//
// Designernamn (Carl Malmsten, Arne Jacobsen, ...) står med flit i samma lista: prismotorn
// söker i en textklump som innehåller designerkolumnen, och på vintagemöbler ÄR designern
// det annonsen säljs under.

export interface KnownBrand {
  name: string;
  /** ungefärligt antal annonser i prismotorns korpus — styr sorteringen i väljaren */
  listings: number;
}

export const KNOWN_BRANDS: KnownBrand[] = [
  { name: "IKEA", listings: 306834 },
  { name: "Mio", listings: 75459 },
  { name: "Carl Malmsten", listings: 33202 },
  { name: "Bruno Mathsson", listings: 22484 },
  { name: "DUX", listings: 18477 },
  { name: "Jysk", listings: 18328 },
  { name: "Svenskt Tenn", listings: 17256 },
  { name: "Hay", listings: 15201 },
  { name: "Fritz Hansen", listings: 14530 },
  { name: "Yngve Ekström", listings: 11522 },
  { name: "Swedese", listings: 11404 },
  { name: "Josef Frank", listings: 9684 },
  { name: "String", listings: 8956 },
  { name: "Arne Jacobsen", listings: 7915 },
  { name: "Kinnarps", listings: 7328 },
  { name: "Sweef", listings: 6622 },
  { name: "Bolia", listings: 5913 },
  { name: "Alvar Aalto", listings: 5528 },
  { name: "Norell", listings: 5082 },
  { name: "Englesson", listings: 4987 },
  { name: "Stolab", listings: 4857 },
  { name: "Vitra", listings: 4674 },
  { name: "Artek", listings: 4670 },
  { name: "Norrgavel", listings: 4346 },
  { name: "Muuto", listings: 4140 },
  { name: "Ellos", listings: 3782 },
  { name: "Rowico", listings: 3622 },
  { name: "Hans J Wegner", listings: 3568 },
  { name: "Jensen", listings: 3484 },
  { name: "Källemo", listings: 3446 },
  { name: "Karl Andersson & Söner", listings: 3431 },
  { name: "Montana", listings: 3423 },
  { name: "Lammhults", listings: 3286 },
  { name: "Jotex", listings: 3221 },
  { name: "Kartell", listings: 2733 },
  { name: "Thonet", listings: 2592 },
  { name: "KungSängen", listings: 2546 },
  { name: "Fogia", listings: 2531 },
  { name: "Ilva", listings: 2459 },
  { name: "Stressless", listings: 2424 },
  { name: "Ekornes", listings: 2398 },
  { name: "BoConcept", listings: 2329 },
  { name: "Furninova", listings: 2119 },
  { name: "TEMPUR", listings: 2112 },
  { name: "Gubi", listings: 1853 },
  { name: "Eilersen", listings: 1799 },
  { name: "Granit", listings: 1765 },
  { name: "Elfa", listings: 1704 },
  { name: "Hästens", listings: 1696 },
  { name: "Gärsnäs", listings: 1631 },
  { name: "ASPLUND", listings: 1612 },
  { name: "Carl Hansen", listings: 1567 },
  { name: "Chilli", listings: 1479 },
  { name: "House Doctor", listings: 1452 },
  { name: "Johanson Design", listings: 1326 },
  { name: "Essem Design", listings: 1319 },
  { name: "Newport", listings: 1303 },
  { name: "Blå Station", listings: 1265 },
  { name: "Hilding", listings: 1265 },
  { name: "Mavis", listings: 1258 },
  { name: "Edsbyn", listings: 1204 },
  { name: "Maze", listings: 1178 },
  { name: "Herman Miller", listings: 1021 },
  { name: "&Tradition", listings: 1018 },
  { name: "Magis", listings: 987 },
  { name: "Venture Home", listings: 957 },
  { name: "Fredericia", listings: 945 },
  { name: "Ekens", listings: 865 },
  { name: "Offecct", listings: 831 },
  { name: "Cassina", listings: 815 },
  { name: "Knoll", listings: 793 },
  { name: "Fatboy", listings: 781 },
  { name: "Getama", listings: 701 },
  { name: "Sofacompany", listings: 674 },
  { name: "Ferm Living", listings: 659 },
  { name: "Arper", listings: 655 },
  { name: "Verner Panton", listings: 640 },
  { name: "Trademax", listings: 564 },
  { name: "Bruksbo", listings: 556 },
  { name: "Nirvan Richter", listings: 556 },
  { name: "Slettvoll", listings: 556 },
  { name: "Bröderna Anderssons", listings: 522 },
  { name: "Audo Copenhagen", listings: 510 },
  { name: "Materia", listings: 510 },
  { name: "Skandiform", listings: 503 },
  { name: "EFG", listings: 465 },
  { name: "Design House Stockholm", listings: 461 },
  { name: "Nordal", listings: 427 },
  { name: "Zara Home", listings: 427 },
  { name: "Normann Copenhagen", listings: 407 },
  { name: "Georg Jensen", listings: 388 },
  { name: "Horreds", listings: 388 },
  { name: "Skagerak", listings: 369 },
  { name: "Designtorget", listings: 366 },
  { name: "Zanotta", listings: 358 },
  { name: "Claesson Koivisto Rune", listings: 354 },
  { name: "Rusta", listings: 346 },
  { name: "Torkelson", listings: 343 },
  { name: "Tom Dixon", listings: 327 },
  { name: "Massproductions", listings: 305 },
  { name: "Natuzzi", listings: 305 },
  { name: "Nordiska Galleriet", listings: 305 },
  { name: "EM Home", listings: 297 },
  { name: "Hemtex", listings: 293 },
  { name: "Bloomingville", listings: 289 },
  { name: "Frost", listings: 266 },
  { name: "Menu", listings: 266 },
  { name: "Fameg", listings: 255 },
  { name: "Ligne Roset", listings: 251 },
  { name: "Layered", listings: 232 },
  { name: "Carpe Diem Beds", listings: 228 },
  { name: "Viking Beds", listings: 217 },
  { name: "Martela", listings: 213 },
  { name: "Erik Jørgensen", listings: 205 },
  { name: "Sika Design", listings: 190 },
  { name: "Frama", listings: 183 },
  { name: "Mille Notti", listings: 179 },
  { name: "USM", listings: 175 },
  { name: "Pedrali", listings: 167 },
  { name: "Orrefors", listings: 163 },
  { name: "Interstil", listings: 160 },
  { name: "Norm", listings: 152 },
  { name: "String Furniture", listings: 152 },
  { name: "Adea", listings: 144 },
  { name: "Minotti", listings: 144 },
  { name: "Åhléns Home", listings: 141 },
  { name: "Sängfabriken", listings: 137 },
  { name: "Artilleriet", listings: 129 },
  { name: "B&B Italia", listings: 129 },
  { name: "Klippan Yllefabrik", listings: 129 },
  { name: "New Works", listings: 125 },
  { name: "AYTM", listings: 118 },
  { name: "Flexform", listings: 114 },
  { name: "H&M Home", listings: 114 },
  { name: "Hk Living", listings: 114 },
  { name: "Sits", listings: 104 },
  { name: "Alessi", listings: 99 },
  { name: "Glimakra", listings: 99 },
  { name: "Mitab", listings: 99 },
  { name: "Poliform", listings: 91 },
  { name: "Marimekko", listings: 87 },
  { name: "Søstrene Grene", listings: 87 },
  { name: "Rolf Benz", listings: 83 },
  { name: "Artemide", listings: 80 },
  { name: "Auping", listings: 80 },
  { name: "Abstracta", listings: 76 },
  { name: "Isku", listings: 76 },
  { name: "Louis Poulsen", listings: 76 },
  { name: "Verpan", listings: 76 },
  { name: "Walter Knoll", listings: 76 },
  { name: "Woud", listings: 76 },
  { name: "Flos", listings: 72 },
  { name: "Broste Copenhagen", listings: 68 },
  { name: "Furniturebox", listings: 68 },
  { name: "Zebra Collection", listings: 68 },
  { name: "Lagerhaus", listings: 64 },
  { name: "Himolla", listings: 61 },
  { name: "Umage", listings: 57 },
  { name: "by Lassen", listings: 53 },
  { name: "Ire Möbel", listings: 53 },
  { name: "Riviera Maison", listings: 53 },
  { name: "Astro", listings: 45 },
  { name: "Bruunmunch", listings: 45 },
  { name: "Note Design", listings: 45 },
  { name: "Porsche", listings: 45 },
  { name: "Roche Bobois", listings: 45 },
  { name: "Vipp", listings: 45 },
  { name: "Wilkhahn", listings: 45 },
  { name: "Zweed", listings: 45 },
  { name: "Northern", listings: 41 },
  { name: "Gotessons", listings: 38 },
  { name: "Iittala", listings: 38 },
  { name: "Lundbergs Möbler", listings: 38 },
  { name: "Vaarnii", listings: 38 },
  { name: "Herstal", listings: 34 },
  { name: "Nikari", listings: 30 },
  { name: "Nola", listings: 30 },
  { name: "Eva Solo", listings: 26 },
  { name: "Jonathan Adler", listings: 26 },
  { name: "Kosta Boda", listings: 26 },
  { name: "Lene Bjerre", listings: 26 },
  { name: "Lundia", listings: 22 },
  { name: "Made By Choice", listings: 22 },
  { name: "Molteni", listings: 22 },
  { name: "Stelton", listings: 22 },
  { name: "Kay Bojesen", listings: 19 },
  { name: "Blastation", listings: 15 },
  { name: "Duxiana", listings: 15 },
  { name: "Dyberg Larsen", listings: 15 },
  { name: "Le Klint", listings: 15 },
  { name: "Rosendahl", listings: 15 },
  { name: "Arcchio", listings: 7 },
  { name: "Design Letters", listings: 7 },
  { name: "Nordlux", listings: 7 },
  { name: "Perfect Home", listings: 7 },
  { name: "Sotka", listings: 7 },
  { name: "Villeroy & Boch", listings: 7 },
  { name: "aida", listings: 3 },
  { name: "Bing & Grøndahl", listings: 3 },
  { name: "Klaus Haapaniemi", listings: 3 },
  { name: "Secto", listings: 3 },
  { name: "Fog & Mørup", listings: 0 },
  { name: "Holmegaard", listings: 0 },
  { name: "Lapuan Kankurit", listings: 0 },
];

